### ISSUE TITLE
Safe operation detection fails after World.regenerateChunk

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit-Premium#91]
When bukkit world regenerateChunk is called it unloads the chunk but ChunkUnloadEvent event is not called.

**Comment by stevmei** [comment]
Running version 3.4.1, not fixed:

http://pastebin.com/dQn2Ecua

**Comment by SBPrime** [comment]
@sigmaroot Since the issue is not yet closed this means that I did not have time fix this.

**Comment by SBPrime** [comment]
From forums: I have seen this error using //regen, fixwater and /cut.

**Comment by SBPrime** [comment]
Fixed in 3.4.9

**Comment by stevmei** [comment]
I guess, this is not fixed... :(

https://pastebin.com/88iVzRY7

A player used //regen
